spring.application.name=techserv
server.port=8008


# ?????? ?????? ??? ???? LocalDateTime
spring.jackson.date-format=yyyy-MM-dd 


# DB settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/techservice
spring.datasource.username=anton
spring.datasource.password=anton
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=false
token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855


spring.mail.protocol=smtps
spring.mail.port=465
spring.mail.host=smtp.yandex.ru
spring.mail.username=
spring.mail.password=

api.base-url=http://localhost:5000
spring.profiles.active=feign